### ISSUE TITLE
failed to install on Google Cloud SQL

### ISSUE THREAD

**Issue by ferreiro** [spa5k/uids-postgres#4]
hey there, Love your library <3. I'm using cloud SQL but it says it's not available. how can I make it happen and install it over there?

**Comment by spa5k** [comment]
Hey, sorry for late reply, but it either needs you to manually build the postgres image, or install it as the debian release file, you can find more info on official pgrx site and discord

**Comment by spa5k** [comment]
https://github.com/spa5k/uids-postgres/issues/5#issuecomment-2487623096

Similar to this, you can also try doing it directly, as UUID_V7 is quite popular and should be supported, or TypeID which is again pure SQL
